=== MikezuGe/webglib/schemas/geometry.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Geometry",
  "$comment": "A geometry",
  "type": "object",
  "required": ["vertices", "attributes", "stepModes", "primitive"],
  "additionalProperties": false,
  "properties": {
    "attributes": {
      "type": "array",
      "minLength": 1,
      "items": {
        "type": "array",
        "minLength": 1,
        "uniqueItems": true,
        "items": {
          "type": "string",
          "enum": ["position", "uv", "normal"]
        }
      }
    },
    "stepModes": {
      "type": "array",
      "minLength": 1,
      "items": {
        "type": "string",
        "enum": ["vertex", "instance"]
      }
    },
    "primitive": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "cullMode": {
          "enum": ["none", "front", "back"]
        },
        "frontFace": {
          "enum": ["ccw", "cw"]
        },
        "stripIndexFormat": {
          "enum": ["uint16", "uint32"]
        },
        "topology": {
          "enum": [
            "point-list",
            "line-list",
            "line-strip",
            "triangle-list",
            "triangle-strip"
          ]
        },
        "unclippedDepth": {
          "type": "boolean"
        }
      }
    },
    "vertices": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "indices": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  }
}

=== MikezuGe/webglib/src/assets/geometries/geometry1.json
{
  "attributes": [["position", "uv", "normal"]],
  "stepModes": ["vertex"],
  "primitive": {
    "cullMode": "back",
    "frontFace": "ccw",
    "topology": "triangle-list"
  },
  "vertices": [
    [
      -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, -1.0, 0.0, 0.0, 1.0, 0.0,
      0.0, -1.0, 1.0, -1.0, 0.0, 1.0, 1.0, 0.0, 0.0, -1.0, 1.0, 1.0, 0.0, 1.0,
      0.0, 0.0, 0.0, -1.0
    ]
  ],
  "indices": [0, 1, 2, 0, 2, 3]
}
